version: '3.9'

services:
  grafana:
    image: grafana/grafana:11.2.2
    env_file:
      - .grafana
    container_name: mk_grafana
    restart: always
    volumes:
      # Data persistency
      # mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - /srv/docker/grafana/data:/var/lib/grafana
    ports:
      - "3000:3000"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      # Data persistency
      # mkdir -p /srv/docker/influxdb/data ; chown -R 1000:1000 /srv/docker/influxdb/data ; chmod -R 775 /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb2
    env_file:
      - .influxdb

  prometheus:
    image: prom/prometheus
    env_file:
      - .prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=1y"
    user: ${CURRENT_USER}
    container_name: mk_prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus
      - ./prometheus/data/:/prometheus
    ports:
      - "9090:9090"

  snmp_exporter:
    image: prom/snmp-exporter
    container_name: mk_snmp_exporter
    restart: always
    volumes:
      - ./snmp/:/etc/snmp_exporter/
    ports:
      - "9116:9116"
    depends_on:
      - prometheus
